name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # Ensure this matches your deployment branch

jobs:
  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group  # Ensures only one action runs at a time

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  # Ensure it uses the updated token
        run: |
          flyctl auth whoami  # Verifies Fly.io authentication before deploying
          flyctl deploy --remote-only
